-- MySQL Script generated by MySQL Workbench
-- 03/10/17 01:28:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`ENDERECO` (
  `end_id` INT(11) NOT NULL AUTO_INCREMENT,
  `end_pais` VARCHAR(60) NOT NULL,
  `end_estado` CHAR(2) NOT NULL,
  `end_cidade` VARCHAR(100) NOT NULL,
  `end_cep` VARCHAR(13) NOT NULL,
  `end_bairro` VARCHAR(45) NOT NULL,
  `end_distrito` VARCHAR(45) NOT NULL,
  `end_rua` VARCHAR(45) NOT NULL,
  `end_numero` INT(9) NOT NULL,
  PRIMARY KEY (`end_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`PESSOA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PESSOA` (
  `pes_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pes_nome` VARCHAR(100) NOT NULL,
  `pes_pai` VARCHAR(100) NOT NULL,
  `pes_mae` VARCHAR(100) NOT NULL,
  `pes_rg` VARCHAR(15) NOT NULL,
  `pes_cpf` VARCHAR(15) NOT NULL,
  `pes_data` DATE NOT NULL,
  `pes_tipo` INT(1) NOT NULL,
  `pes_email` VARCHAR(100) NOT NULL,
  `pes_estado_civil` INT(1) NOT NULL,
  `pes_cidadania` VARCHAR(45) NOT NULL,
  `pes_genero` VARCHAR(25) NOT NULL,
  `pes_sexo_biologico` VARCHAR(25) NOT NULL,
  `pes_telefone` VARCHAR(15) NOT NULL,
  `pes_endereco` INT(11) NOT NULL,
  PRIMARY KEY (`pes_id`),
  INDEX `fk_PESSOA_ENDERECO1_idx` (`pes_endereco` ASC),
  CONSTRAINT `fk_PESSOA_ENDERECO1`
    FOREIGN KEY (`pes_endereco`)
    REFERENCES `hospital`.`ENDERECO` (`end_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`USUARIO` (
  `usu_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usu_nome` VARCHAR(60) NOT NULL,
  `usu_senha` VARCHAR(64) NOT NULL,
  `usu_email` VARCHAR(45) NOT NULL,
  `usu_ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `usu_tipo` INT(11) NOT NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`MODULOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`MODULOS` (
  `mod_id` INT(11) NOT NULL AUTO_INCREMENT,
  `mod_nome` VARCHAR(45) NOT NULL,
  `mod_descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`mod_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`PERMISSOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PERMISSOES` (
  `per_id` INT(11) NOT NULL AUTO_INCREMENT,
  `per_modulo` INT(11) NOT NULL,
  `per_nivel` INT(1) NOT NULL,
  `USUARIO_usu_id` INT(4) NOT NULL,
  PRIMARY KEY (`per_id`),
  INDEX `fk_PERMISSOES_USUARIO1_idx` (`USUARIO_usu_id` ASC),
  INDEX `fk_PERMISSOES_MODULOS1_idx` (`per_modulo` ASC),
  CONSTRAINT `fk_PERMISSOES_USUARIO1`
    FOREIGN KEY (`USUARIO_usu_id`)
    REFERENCES `hospital`.`USUARIO` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERMISSOES_MODULOS1`
    FOREIGN KEY (`per_modulo`)
    REFERENCES `hospital`.`MODULOS` (`mod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`SETOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`SETOR` (
  `set_id` INT(11) NOT NULL AUTO_INCREMENT,
  `set_nome` VARCHAR(60) NOT NULL,
  `set_descricao` VARCHAR(255) NOT NULL,
  `set_responsavel` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`set_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`FUNCIONARIO` (
  `fun_id` INT(11) NOT NULL AUTO_INCREMENT,
  `fun_cargo` VARCHAR(45) NOT NULL,
  `fun_horario` TIME NOT NULL,
  `fun_inscricao` INT(9) NOT NULL,
  `fun_turno` INT(1) NOT NULL,
  `PERMISSOES_per_id` INT(4) NOT NULL,
  `USUARIO_usu_id` INT(4) NOT NULL,
  `SETOR_set_id` INT(4) NOT NULL,
  `PESSOA_pes_id` INT(4) NOT NULL,
  INDEX `fk_FUNCIONARIOS_PERMISSOES1_idx` (`PERMISSOES_per_id` ASC),
  INDEX `fk_FUNCIONARIOS_USUARIO1_idx` (`USUARIO_usu_id` ASC),
  PRIMARY KEY (`fun_id`),
  INDEX `fk_FUNCIONARIOS_SETOR1_idx` (`SETOR_set_id` ASC),
  INDEX `fk_FUNCIONARIO_PESSOA1_idx` (`PESSOA_pes_id` ASC),
  CONSTRAINT `fk_FUNCIONARIOS_PERMISSOES1`
    FOREIGN KEY (`PERMISSOES_per_id`)
    REFERENCES `hospital`.`PERMISSOES` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUNCIONARIOS_USUARIO1`
    FOREIGN KEY (`USUARIO_usu_id`)
    REFERENCES `hospital`.`USUARIO` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUNCIONARIOS_SETOR1`
    FOREIGN KEY (`SETOR_set_id`)
    REFERENCES `hospital`.`SETOR` (`set_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUNCIONARIO_PESSOA1`
    FOREIGN KEY (`PESSOA_pes_id`)
    REFERENCES `hospital`.`PESSOA` (`pes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`ESPECIALIZACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`ESPECIALIZACAO` (
  `esp_id` INT(11) NOT NULL AUTO_INCREMENT,
  `esp_nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`esp_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`CONSULTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`CONSULTA` (
  `con_id` INT(11) NOT NULL AUTO_INCREMENT,
  `con_data` DATETIME NOT NULL,
  `con_status` VARCHAR(45) NOT NULL,
  `con_urgencia` TINYINT(1) NOT NULL,
  PRIMARY KEY (`con_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`MEDICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`MEDICO` (
  `med_id` INT(11) NOT NULL AUTO_INCREMENT,
  `med_crm` VARCHAR(45) NOT NULL,
  `ESPECIALIZACAO_esp_id` INT(4) NOT NULL,
  `FUNCIONARIO_fun_id` INT(4) NOT NULL,
  `CONSULTA_con_id` INT(4) NOT NULL,
  PRIMARY KEY (`med_id`),
  INDEX `fk_MEDICO_ESPECIALIZACAO1_idx` (`ESPECIALIZACAO_esp_id` ASC),
  INDEX `fk_MEDICO_FUNCIONARIO1_idx` (`FUNCIONARIO_fun_id` ASC),
  INDEX `fk_MEDICO_CONSULTA1_idx` (`CONSULTA_con_id` ASC),
  CONSTRAINT `fk_MEDICO_ESPECIALIZACAO1`
    FOREIGN KEY (`ESPECIALIZACAO_esp_id`)
    REFERENCES `hospital`.`ESPECIALIZACAO` (`esp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEDICO_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_fun_id`)
    REFERENCES `hospital`.`FUNCIONARIO` (`fun_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEDICO_CONSULTA1`
    FOREIGN KEY (`CONSULTA_con_id`)
    REFERENCES `hospital`.`CONSULTA` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`FUMANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`FUMANTE` (
  `fum_id` INT(11) NOT NULL AUTO_INCREMENT,
  `fum_passivo` TINYINT(1) NOT NULL,
  `fum_cigarros_dia` INT(2) NOT NULL,
  `fum_idade_inicio` DATE NOT NULL,
  `fum_idade_fim` DATE NOT NULL,
  PRIMARY KEY (`fum_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`DROGAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`DROGAS` (
  `dro_id` INT(11) NOT NULL AUTO_INCREMENT,
  `dro_nome_vulgar` VARCHAR(45) NOT NULL,
  `dro_nome` VARCHAR(45) NOT NULL,
  `dro_toxicidade` VARCHAR(45) NOT NULL,
  `dro_codigo` VARCHAR(45) NOT NULL,
  `dro_catergoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`QUIMICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`QUIMICO` (
  `qui_id` INT(11) NOT NULL AUTO_INCREMENT,
  `qui_intravenosso` TINYINT(1) NOT NULL,
  `qui_idade_fim` DATE NOT NULL,
  `qui_idade_inicio` DATE NOT NULL,
  `qui_ex_viciado` TINYINT(1) NOT NULL,
  `qui_outra` INT NOT NULL,
  PRIMARY KEY (`qui_id`),
  INDEX `fk_QUIMICO_DROGAS1_idx` (`qui_outra` ASC),
  CONSTRAINT `fk_QUIMICO_DROGAS1`
    FOREIGN KEY (`qui_outra`)
    REFERENCES `hospital`.`DROGAS` (`dro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`DIETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`DIETA` (
  `die_id` INT(11) NOT NULL AUTO_INCREMENT,
  `die_cafe` INT(1) NOT NULL,
  `die_sal` VARCHAR(45) NOT NULL,
  `die_autonomo` VARCHAR(45) NOT NULL,
  `die_refeicoes_dia` INT(1) NOT NULL,
  `die_regime` VARCHAR(45) NOT NULL,
  `die_comentarios` VARCHAR(100) NOT NULL,
  `die_vegetariano` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`die_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`PRATICA_SEXO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PRATICA_SEXO` (
  `prs_id` INT(11) NOT NULL AUTO_INCREMENT,
  `prs_prostituta` TINYINT(1) NOT NULL,
  `prs_anal` TINYINT(1) NOT NULL,
  `prs_oral` TINYINT(1) NOT NULL,
  `prs_sexo_com_prostituta` TINYINT(1) NOT NULL,
  PRIMARY KEY (`prs_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`SEXUALIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`SEXUALIDADE` (
  `sex_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sex_parceiros` INT(2) NOT NULL,
  `sex_pref_sexual` VARCHAR(45) NOT NULL,
  `sex_seguro` VARCHAR(45) NOT NULL,
  `sex_idade_iniciacao` INT(2) NOT NULL,
  `sex_pratica_sexo` INT(11) NOT NULL,
  `sex_contracep` TINYINT(1) NOT NULL,
  PRIMARY KEY (`sex_id`),
  INDEX `fk_SEXUALIDADE_PRATICA_SEXO1_idx` (`sex_pratica_sexo` ASC),
  CONSTRAINT `fk_SEXUALIDADE_PRATICA_SEXO1`
    FOREIGN KEY (`sex_pratica_sexo`)
    REFERENCES `hospital`.`PRATICA_SEXO` (`prs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`ALCOOL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`ALCOOL` (
  `alc_id` INT(11) NOT NULL AUTO_INCREMENT,
  `alc_alcoolatra` TINYINT(1) NOT NULL,
  `alc_ex_alcoolatra` TINYINT(1) NOT NULL,
  `alc_idade_inicio` DATE NOT NULL,
  `alc_idade_fim` DATE NOT NULL,
  `alc_vinho_dia` VARCHAR(45) NOT NULL,
  `alc_cervejas_dia` INT(2) NOT NULL,
  `alc_destilados_dia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`alc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`SONO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`SONO` (
  `son_id` INT(11) NOT NULL AUTO_INCREMENT,
  `son_horas` TIME NOT NULL,
  `son_minutos_dia` TIME NOT NULL,
  PRIMARY KEY (`son_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`EXERCICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`EXERCICIO` (
  `exe_id` INT(11) NOT NULL AUTO_INCREMENT,
  `exe_pratica` TINYINT(1) NOT NULL,
  `exe_minutos_dia` TIME NOT NULL,
  PRIMARY KEY (`exe_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`ESTILO_DE_VIDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`ESTILO_DE_VIDA` (
  `edv_id` INT(11) NOT NULL AUTO_INCREMENT,
  `edv_vicios` INT NOT NULL,
  `edv_sono` INT NOT NULL,
  `edv_exercicio` INT NOT NULL,
  `DIETA_die_id` INT NOT NULL,
  `SEXUALIDADE_sex_id` INT NOT NULL,
  PRIMARY KEY (`edv_id`),
  INDEX `fk_ESTILO_VIDA_FUMANTE1_idx` (`edv_vicios` ASC),
  INDEX `fk_ESTILO_VIDA_DIETA1_idx` (`DIETA_die_id` ASC),
  INDEX `fk_ESTILO_VIDA_SEXUALIDADE1_idx` (`SEXUALIDADE_sex_id` ASC),
  INDEX `fk_ESTILO_VIDA_SONO1_idx` (`edv_sono` ASC),
  INDEX `fk_ESTILO_VIDA_EXERCICIO1_idx` (`edv_exercicio` ASC),
  CONSTRAINT `fk_ESTILO_VIDA_FUMANTE1`
    FOREIGN KEY (`edv_vicios`)
    REFERENCES `hospital`.`FUMANTE` (`fum_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTILO_VIDA_QUIMICO1`
    FOREIGN KEY (`edv_vicios`)
    REFERENCES `hospital`.`QUIMICO` (`qui_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTILO_VIDA_DIETA1`
    FOREIGN KEY (`DIETA_die_id`)
    REFERENCES `hospital`.`DIETA` (`die_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTILO_VIDA_SEXUALIDADE1`
    FOREIGN KEY (`SEXUALIDADE_sex_id`)
    REFERENCES `hospital`.`SEXUALIDADE` (`sex_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTILO_VIDA_ALCOOL1`
    FOREIGN KEY (`edv_vicios`)
    REFERENCES `hospital`.`ALCOOL` (`alc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTILO_VIDA_SONO1`
    FOREIGN KEY (`edv_sono`)
    REFERENCES `hospital`.`SONO` (`son_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTILO_VIDA_EXERCICIO1`
    FOREIGN KEY (`edv_exercicio`)
    REFERENCES `hospital`.`EXERCICIO` (`exe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`SOCIO_ECONOMICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`SOCIO_ECONOMICO` (
  `soe_id` INT(11) NOT NULL AUTO_INCREMENT,
  `soe_detento` TINYINT(1) NOT NULL,
  `soe_familia_monoparamental` TINYINT(1) NOT NULL,
  `soe_gravidez_adolescencia` TINYINT(1) NOT NULL,
  `soe_area_de_risco` TINYINT(1) NOT NULL,
  `soe_abuso_sexual` TINYINT(1) NOT NULL,
  `soe_ex_detento` TINYINT(1) NOT NULL,
  `soe_trabalho_infantil` TINYINT(1) NOT NULL,
  `soe_violencia_domestica` TINYINT(1) NOT NULL,
  PRIMARY KEY (`soe_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`GENETICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`GENETICA` (
  `gen_id` INT(11) NOT NULL AUTO_INCREMENT,
  `gen_proteina` VARCHAR(45) NOT NULL,
  `gen_cromosomos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`gen_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`GRUPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`GRUPO` (
  `grp_id` INT(11) NOT NULL AUTO_INCREMENT,
  `grp_descricao` VARCHAR(155) NOT NULL,
  `grp_informacao` VARCHAR(155) NOT NULL,
  `grp_codigo` INT(9) NOT NULL,
  PRIMARY KEY (`grp_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`PATOLOGIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PATOLOGIA` (
  `ptl_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ptl_codigo` INT(10) NOT NULL,
  `ptl_nome` VARCHAR(45) NOT NULL,
  `ptl_categoria` VARCHAR(45) NOT NULL,
  `ptl_informacao` VARCHAR(255) NOT NULL,
  `ptl_gene` INT NOT NULL,
  `ptl_grupo` INT NOT NULL,
  PRIMARY KEY (`ptl_id`),
  INDEX `fk_PATOLOGIA_GENETICA1_idx` (`ptl_gene` ASC),
  INDEX `fk_PATOLOGIA_GRUPO1_idx` (`ptl_grupo` ASC),
  CONSTRAINT `fk_PATOLOGIA_GENETICA1`
    FOREIGN KEY (`ptl_gene`)
    REFERENCES `hospital`.`GENETICA` (`gen_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PATOLOGIA_GRUPO1`
    FOREIGN KEY (`ptl_grupo`)
    REFERENCES `hospital`.`GRUPO` (`grp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`PLANO_DE_SAUDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PLANO_DE_SAUDE` (
  `pds_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pds_convenio` VARCHAR(60) NOT NULL,
  `pds_sus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pds_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`PRESCRICAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PRESCRICAO` (
  `pre_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pre_data` VARCHAR(45) NOT NULL,
  `pre_verificada` TINYINT(1) NOT NULL,
  `pre_info` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PACIENTE` (
  `pac_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pac_tipo_sangue` CHAR(2) NOT NULL,
  `pac_remedio` VARCHAR(45) NOT NULL,
  `pac_doenca` VARCHAR(45) NOT NULL,
  `pac_educacao` VARCHAR(100) NOT NULL,
  `pac_profissao` VARCHAR(100) NOT NULL,
  `pac_hospitalizado` TINYINT(1) NOT NULL,
  `PESSOA_id_dados` INT NOT NULL,
  `ESTILO_DE_VIDA_edv_id` INT NOT NULL,
  `SOCIO_ECONOMICO_soe_id` INT(4) NOT NULL,
  `PATOLOGIA_ptl_id` INT(4) NOT NULL,
  `PLANO_DE_SAUDE_pds_id` INT(4) NOT NULL,
  `CONSULTA_con_id` INT(4) NOT NULL,
  `PRESCRICAO_pre_id` INT NOT NULL,
  INDEX `fk_PACIENTE_PESSOA1_idx` (`PESSOA_id_dados` ASC),
  INDEX `fk_PACIENTE_ESTILO_DE_VIDA1_idx` (`ESTILO_DE_VIDA_edv_id` ASC),
  INDEX `fk_PACIENTE_SOCIO_ECONOMICO1_idx` (`SOCIO_ECONOMICO_soe_id` ASC),
  INDEX `fk_PACIENTE_PATOLOGIA1_idx` (`PATOLOGIA_ptl_id` ASC),
  INDEX `fk_PACIENTE_PLANO_DE_SAUDE1_idx` (`PLANO_DE_SAUDE_pds_id` ASC),
  INDEX `fk_PACIENTE_CONSULTA1_idx` (`CONSULTA_con_id` ASC),
  INDEX `fk_PACIENTE_PRESCRICAO1_idx` (`PRESCRICAO_pre_id` ASC),
  PRIMARY KEY (`pac_id`),
  CONSTRAINT `fk_PACIENTE_PESSOA1`
    FOREIGN KEY (`PESSOA_id_dados`)
    REFERENCES `hospital`.`PESSOA` (`pes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_ESTILO_DE_VIDA1`
    FOREIGN KEY (`ESTILO_DE_VIDA_edv_id`)
    REFERENCES `hospital`.`ESTILO_DE_VIDA` (`edv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_SOCIO_ECONOMICO1`
    FOREIGN KEY (`SOCIO_ECONOMICO_soe_id`)
    REFERENCES `hospital`.`SOCIO_ECONOMICO` (`soe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_PATOLOGIA1`
    FOREIGN KEY (`PATOLOGIA_ptl_id`)
    REFERENCES `hospital`.`PATOLOGIA` (`ptl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_PLANO_DE_SAUDE1`
    FOREIGN KEY (`PLANO_DE_SAUDE_pds_id`)
    REFERENCES `hospital`.`PLANO_DE_SAUDE` (`pds_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_CONSULTA1`
    FOREIGN KEY (`CONSULTA_con_id`)
    REFERENCES `hospital`.`CONSULTA` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_PRESCRICAO1`
    FOREIGN KEY (`PRESCRICAO_pre_id`)
    REFERENCES `hospital`.`PRESCRICAO` (`pre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`QUADRO_CLINICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`QUADRO_CLINICO` (
  `qcl_id` INT(11) NOT NULL AUTO_INCREMENT,
  `qcl_quadro` VARCHAR(60) NOT NULL,
  `qcl_gravidade` INT(1) NOT NULL,
  PRIMARY KEY (`qcl_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`TRIAGEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`TRIAGEM` (
  `tri_id` INT(5) NOT NULL AUTO_INCREMENT,
  `tri_temperatura` VARCHAR(25) NOT NULL,
  `tri_pressao` VARCHAR(25) NOT NULL,
  `tri_peso` FLOAT NOT NULL,
  `tri_altura` FLOAT NOT NULL,
  `tri_batimento` VARCHAR(25) NOT NULL,
  `tri_classe_risco` VARCHAR(25) NOT NULL,
  `tri_oxigenacao` VARCHAR(25) NOT NULL,
  `tri_respiracao` VARCHAR(25) NOT NULL,
  `PACIENTE_pac_id` INT(5) NOT NULL,
  `QUADRO_CLINICO_qcl_id` INT(4) NOT NULL,
  PRIMARY KEY (`tri_id`),
  INDEX `fk_TRIAGEM_PACIENTE1_idx` (`PACIENTE_pac_id` ASC),
  INDEX `fk_TRIAGEM_QUADRO_CLINICO1_idx` (`QUADRO_CLINICO_qcl_id` ASC),
  CONSTRAINT `fk_TRIAGEM_PACIENTE1`
    FOREIGN KEY (`PACIENTE_pac_id`)
    REFERENCES `hospital`.`PACIENTE` (`pac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRIAGEM_QUADRO_CLINICO1`
    FOREIGN KEY (`QUADRO_CLINICO_qcl_id`)
    REFERENCES `hospital`.`QUADRO_CLINICO` (`qcl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PRODUTO` (
  `prt_id` INT(11) NOT NULL AUTO_INCREMENT,
  `prt_preco_custo` FLOAT NOT NULL,
  `prt_preco_lista` FLOAT NOT NULL,
  `prt_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`prt_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`MEDICAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`MEDICAMENTO` (
  `med_id` INT(11) NOT NULL AUTO_INCREMENT,
  `med_descricao` VARCHAR(150) NOT NULL,
  `med_nome` VARCHAR(45) NOT NULL,
  `med_indicacao` VARCHAR(150) NOT NULL,
  `med_componente_ativo` VARCHAR(45) NOT NULL,
  `med_unidade` INT(3) NOT NULL,
  `med_armazenamento` VARCHAR(45) NOT NULL,
  `med_concentracao` VARCHAR(45) NOT NULL,
  `med_categoria` VARCHAR(45) NOT NULL,
  `med_vacina` VARCHAR(45) NOT NULL,
  `PRODUTO_prt_id` INT(4) NOT NULL,
  PRIMARY KEY (`med_id`),
  INDEX `fk_MEDICAMENTO_PRODUTO1_idx` (`PRODUTO_prt_id` ASC),
  CONSTRAINT `fk_MEDICAMENTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_prt_id`)
    REFERENCES `hospital`.`PRODUTO` (`prt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`ENFERMEIRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`ENFERMEIRO` (
  `enf_id` INT(11) NOT NULL AUTO_INCREMENT,
  `enf_registro` VARCHAR(45) NOT NULL,
  `FUNCIONARIO_fun_id` INT(4) NOT NULL,
  PRIMARY KEY (`enf_id`),
  INDEX `fk_ENFERMEIRO_FUNCIONARIO1_idx` (`FUNCIONARIO_fun_id` ASC),
  CONSTRAINT `fk_ENFERMEIRO_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_fun_id`)
    REFERENCES `hospital`.`FUNCIONARIO` (`fun_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`ADMINISTRACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`ADMINISTRACAO` (
  `adm_id` INT(11) NOT NULL AUTO_INCREMENT,
  `adm_funcao` VARCHAR(155) NULL,
  PRIMARY KEY (`adm_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`LOGIN_ACESSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`LOGIN_ACESSO` (
  `log_id` INT(11) NOT NULL AUTO_INCREMENT,
  `log_data` DATETIME NOT NULL,
  `log_ip` VARCHAR(45) NOT NULL,
  `USUARIO_usu_id` INT(4) NOT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_LOGIN_ACESSO_USUARIO1_idx` (`USUARIO_usu_id` ASC),
  CONSTRAINT `fk_LOGIN_ACESSO_USUARIO1`
    FOREIGN KEY (`USUARIO_usu_id`)
    REFERENCES `hospital`.`USUARIO` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`OBITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`OBITO` (
  `obi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `obi_data` DATE NOT NULL,
  `obi_hora` TIME NOT NULL,
  `obi_causamortis` VARCHAR(255) NOT NULL,
  `obi_local` VARCHAR(45) NOT NULL,
  `obi_autopsia` TINYINT(1) NOT NULL,
  `PACIENTE_pac_id` INT(5) NOT NULL,
  PRIMARY KEY (`obi_id`),
  INDEX `fk_OBITO_PACIENTE1_idx` (`PACIENTE_pac_id` ASC),
  CONSTRAINT `fk_OBITO_PACIENTE1`
    FOREIGN KEY (`PACIENTE_pac_id`)
    REFERENCES `hospital`.`PACIENTE` (`pac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`ASSOCIADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`ASSOCIADOS` (
  `ass_id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ass_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`CONSELHO_GERAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`CONSELHO_GERAL` (
  `cog_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cog_presidente` VARCHAR(100) NULL,
  `cog_vice_pesidente` VARCHAR(100) NULL,
  `con_pimeiro_secretario` VARCHAR(45) NULL,
  PRIMARY KEY (`cog_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`CONSELHO_DELIBERATIVO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`CONSELHO_DELIBERATIVO` (
  `cde_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cde_presidente` VARCHAR(100) NULL,
  `cde_vice_presidente` VARCHAR(100) NULL,
  `cde_primeiro_secretario` VARCHAR(100) NULL,
  `cde_segundo_secretario` VARCHAR(100) NULL,
  PRIMARY KEY (`cde_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`MESA_ADMINISTRATIVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`MESA_ADMINISTRATIVA` (
  `mes_id` INT(11) NOT NULL AUTO_INCREMENT,
  `mes_provedor` VARCHAR(100) NULL,
  `mes_vice_provedor` VARCHAR(100) NULL,
  `mes_primeiro_tesoureiro` VARCHAR(100) NULL,
  `mes_segundo_tesoureiro` VARCHAR(100) NULL,
  `mes_primeiro_secretario` VARCHAR(100) NULL,
  `mes_segundo_secretario` VARCHAR(100) NULL,
  `mes_mordomo_geral` VARCHAR(100) NULL,
  PRIMARY KEY (`mes_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`PROVEDORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PROVEDORIA` (
  `pro_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pro_provedor` VARCHAR(100) NULL,
  `pro_vice_provedorl` VARCHAR(100) NULL,
  `pro_superintendente` VARCHAR(100) NULL,
  PRIMARY KEY (`pro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`FAMILIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`FAMILIA` (
  `fam_id` INT(11) NOT NULL AUTO_INCREMENT,
  `fam_nome` VARCHAR(60) NOT NULL,
  `fam_parentesco` VARCHAR(30) NOT NULL,
  `fam_telefone` VARCHAR(15) NOT NULL,
  `fam_email` VARCHAR(60) NOT NULL,
  `PACIENTE_pac_id` INT(5) NOT NULL,
  PRIMARY KEY (`fam_id`),
  INDEX `fk_FAMILIA_PACIENTE1_idx` (`PACIENTE_pac_id` ASC),
  CONSTRAINT `fk_FAMILIA_PACIENTE1`
    FOREIGN KEY (`PACIENTE_pac_id`)
    REFERENCES `hospital`.`PACIENTE` (`pac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`HISTORICO_MENSTRUAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`HISTORICO_MENSTRUAL` (
  `men_id` INT(11) NOT NULL AUTO_INCREMENT,
  `men_data_mens` DATE NOT NULL,
  `men_data_aval` DATE NOT NULL,
  `men_frequencia` VARCHAR(25) NOT NULL,
  `men_duracao` INT(2) NOT NULL,
  `men_dismenorreia` TINYINT(1) NOT NULL,
  `men_normal` TINYINT(1) NOT NULL,
  `MEDICO_med_id` INT(5) NOT NULL,
  PRIMARY KEY (`men_id`),
  INDEX `fk_HISTORICO_MENSTRUAL_MEDICO1_idx` (`MEDICO_med_id` ASC),
  CONSTRAINT `fk_HISTORICO_MENSTRUAL_MEDICO1`
    FOREIGN KEY (`MEDICO_med_id`)
    REFERENCES `hospital`.`MEDICO` (`med_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`OBSTETRIA_GINECOLOGISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`OBSTETRIA_GINECOLOGISTA` (
  `ob_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ob_gravidez_mult` VARCHAR(45) NOT NULL,
  `ob_idade_menarca` INT(2) NOT NULL,
  `ob_gravida` VARCHAR(45) NOT NULL,
  `ob_fertil` VARCHAR(45) NOT NULL,
  `ob_menopausa` TINYINT(1) NOT NULL,
  `ob_idade_menopausa` VARCHAR(45) NOT NULL,
  `ob_num_gravidez` INT(2) NOT NULL,
  `ob_num_prematuros` INT(2) NOT NULL,
  PRIMARY KEY (`ob_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`ACOMPANHAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`ACOMPANHAMENTO` (
  `aco_id` INT(11) NOT NULL AUTO_INCREMENT,
  `aco_autoexame` TINYINT(1) NOT NULL,
  `aco_colcoscopia` TINYINT(1) NOT NULL,
  `aco_papanicolau` TINYINT(1) NOT NULL,
  `aco_mamografia` TINYINT(1) NOT NULL,
  PRIMARY KEY (`aco_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`SINTOMOLOGIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`SINTOMOLOGIA` (
  `sin_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sin_nome` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`sin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`TRIAGEM_has_SINTOMOLOGIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`TRIAGEM_has_SINTOMOLOGIA` (
  `TRIAGEM_tri_id` INT(5) NOT NULL AUTO_INCREMENT,
  `SINTOMOLOGIA_stm_id` INT(4) NOT NULL,
  PRIMARY KEY (`TRIAGEM_tri_id`, `SINTOMOLOGIA_stm_id`),
  INDEX `fk_TRIAGEM_has_SINTOMOLOGIA_SINTOMOLOGIA1_idx` (`SINTOMOLOGIA_stm_id` ASC),
  INDEX `fk_TRIAGEM_has_SINTOMOLOGIA_TRIAGEM1_idx` (`TRIAGEM_tri_id` ASC),
  CONSTRAINT `fk_TRIAGEM_has_SINTOMOLOGIA_TRIAGEM1`
    FOREIGN KEY (`TRIAGEM_tri_id`)
    REFERENCES `hospital`.`TRIAGEM` (`tri_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRIAGEM_has_SINTOMOLOGIA_SINTOMOLOGIA1`
    FOREIGN KEY (`SINTOMOLOGIA_stm_id`)
    REFERENCES `hospital`.`SINTOMOLOGIA` (`sin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`MEDICACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`MEDICACAO` (
  `mco_id` INT(11) NOT NULL AUTO_INCREMENT,
  `mco_ativo` TINYINT(1) NOT NULL,
  `mco_notas` VARCHAR(60) NOT NULL,
  `mco_inicio` DATE NOT NULL,
  `mco_ fim` DATE NOT NULL,
  `mco_horario` TIME NOT NULL,
  `mco_frequencia` VARCHAR(45) NOT NULL,
  `mco_periodo` VARCHAR(45) NOT NULL,
  `mco_duracao` VARCHAR(45) NOT NULL,
  `mco_completou` TINYINT(1) NOT NULL,
  `mco_suspendido` TINYINT(1) NOT NULL,
  `mco_dose` VARCHAR(60) NOT NULL,
  `PRESCRICAO_pre_id` INT(4) NOT NULL,
  PRIMARY KEY (`mco_id`),
  INDEX `fk_MEDICACAO_PRESCRICAO1_idx` (`PRESCRICAO_pre_id` ASC),
  CONSTRAINT `fk_MEDICACAO_PRESCRICAO1`
    FOREIGN KEY (`PRESCRICAO_pre_id`)
    REFERENCES `hospital`.`PRESCRICAO` (`pre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`CIRURGIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`CIRURGIA` (
  `cir_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cir_descricao` VARCHAR(145) NULL,
  `cir_data` DATE NOT NULL,
  `cir_urgencia` TINYINT(1) NULL,
  `cir_cirugiao` VARCHAR(100) NULL,
  `cir_anestesista` VARCHAR(100) NULL,
  `cir_asa_ps` VARCHAR(45) NULL,
  `cir_ferida` VARCHAR(45) NULL,
  PRIMARY KEY (`cir_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`PROCEDIMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PROCEDIMENTOS` (
  `pcd_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pcd_nome` VARCHAR(145) NOT NULL,
  `pcd_codigo` INT(5) NULL,
  PRIMARY KEY (`pcd_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`CONDICAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`CONDICAO` (
  `cnd_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cnd_nome` VARCHAR(145) NOT NULL,
  `cnd_categoria` VARCHAR(145) NULL,
  `cnd_codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`cnd_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`CAMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`CAMA` (
  `cam_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cam_info` VARCHAR(45) NULL,
  `cam_numero` INT(2) NULL,
  `cam_tipo` VARCHAR(45) NULL,
  `cam_suprimento` VARCHAR(45) NULL,
  `cam_estado` VARCHAR(45) NULL,
  `cam_numero_telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`cam_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`ALA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`ALA` (
  `ala_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ala_nome` VARCHAR(45) NULL,
  `ala_andar` INT(2) NULL,
  `ala_genero` VARCHAR(45) NULL,
  `ala_telefone_acesso` VARCHAR(15) NULL,
  `ala_micro-ondas` TINYINT(1) NULL,
  `ala_info` VARCHAR(45) NULL,
  `ala_numero_camas` INT(4) NULL,
  `ala_refrigerador` TINYINT(1) NULL,
  `ala_ar-condionado` TINYINT(1) NULL,
  `ala_banheiro_privativo` TINYINT(1) NULL,
  `ala_televisao` TINYINT(1) NULL,
  `ala_sofa-cama_convidado` TINYINT(1) NULL,
  `ala_estado` VARCHAR(45) NULL,
  `ala_privado` VARCHAR(45) NULL,
  `ala_risco_biologico` VARCHAR(45) NULL,
  `CAMA_cam_id` INT(11) NOT NULL,
  PRIMARY KEY (`ala_id`),
  INDEX `fk_ALA_CAMA1_idx` (`CAMA_cam_id` ASC),
  CONSTRAINT `fk_ALA_CAMA1`
    FOREIGN KEY (`CAMA_cam_id`)
    REFERENCES `hospital`.`CAMA` (`cam_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`SETOR_OPERACIONAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`SETOR_OPERACIONAL` (
  `seo_id` INT(11) NOT NULL AUTO_INCREMENT,
  `seo_nome` VARCHAR(45) NULL,
  `seo_area` VARCHAR(45) NULL,
  PRIMARY KEY (`seo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`SALA_OPERACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`SALA_OPERACAO` (
  `sao_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sao_nome` VARCHAR(45) NULL,
  `sao_numero_camas` INT(2) NULL,
  `sao_estado` VARCHAR(45) NULL,
  PRIMARY KEY (`sao_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`INSTITUICAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`INSTITUICAO` (
  `ins_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ins_nome` VARCHAR(65) NOT NULL,
  `ins_numero_camas` INT(11) NULL,
  `ins_ativo` TINYINT(1) NULL,
  `ins_administracao` INT(4) NULL,
  `ins_nivel_trauma` VARCHAR(45) NULL,
  `ins_tipo` VARCHAR(45) NULL,
  `ins_centro_trauma` VARCHAR(45) NULL,
  `ins_heliporto` TINYINT(1) NULL,
  `ins_numero_sala_operacao` VARCHAR(45) NULL,
  `ALA_ala_id` INT(11) NOT NULL,
  `SETOR_OPERACIONAL_seo_id` INT(11) NOT NULL,
  `SALA_OPERACAO_sao_id` INT(11) NOT NULL,
  PRIMARY KEY (`ins_id`, `SETOR_OPERACIONAL_seo_id`, `SALA_OPERACAO_sao_id`),
  INDEX `fk_INSTITUICAO_ALA1_idx` (`ALA_ala_id` ASC),
  INDEX `fk_INSTITUICAO_SETOR_OPERACIONAL1_idx` (`SETOR_OPERACIONAL_seo_id` ASC),
  INDEX `fk_INSTITUICAO_SALA_OPERACAO1_idx` (`SALA_OPERACAO_sao_id` ASC),
  CONSTRAINT `fk_INSTITUICAO_ALA1`
    FOREIGN KEY (`ALA_ala_id`)
    REFERENCES `hospital`.`ALA` (`ala_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INSTITUICAO_SETOR_OPERACIONAL1`
    FOREIGN KEY (`SETOR_OPERACIONAL_seo_id`)
    REFERENCES `hospital`.`SETOR_OPERACIONAL` (`seo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INSTITUICAO_SALA_OPERACAO1`
    FOREIGN KEY (`SALA_OPERACAO_sao_id`)
    REFERENCES `hospital`.`SALA_OPERACAO` (`sao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`EXAME_ANALISE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`EXAME_ANALISE` (
  `exa_id` INT(11) NOT NULL AUTO_INCREMENT,
  `exa_valor` FLOAT NULL,
  `exa_data` DATE NULL,
  `exa_resultado` VARCHAR(45) NULL,
  `exa_diagnostico` VARCHAR(45) NULL,
  PRIMARY KEY (`exa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`EXAME_SOLICITACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`EXAME_SOLICITACAO` (
  `exs_id` INT(11) NOT NULL AUTO_INCREMENT,
  `exs_estado` VARCHAR(45) NULL,
  `exs_urgente` TINYINT(1) NULL,
  `exs_data` DATE NULL,
  PRIMARY KEY (`exs_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`TESTE_IMAGEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`TESTE_IMAGEM` (
  `tei_id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`tei_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `hospital`.`TESTE_LABORATORIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`TESTE_LABORATORIO` (
  `tel_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tel_analito` VARCHAR(45) NULL,
  `tel_valor_maximo` FLOAT NULL,
  `tel_valor_minimo` FLOAT NULL,
  `tel_unidade_medida` VARCHAR(45) NULL,
  PRIMARY KEY (`tel_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
